install: skip

jobs:
  include:
    - stage: test
      name: "MacOS"
      os: osx
      osx_image: xcode11
      language: java
      script: "./gradlew clean macosX64Test iosX64Test"

    - stage: test
      name: "Linux"
      os: linux
      language: java
      script: "./gradlew clean linuxX64Test"

    - stage: test
      name: "JavaScript"
      language: java
      script: "./gradlew clean jsTest jsNodeTest"

    - stage: test
      name: "JVM"
      language: java
      script: "./gradlew clean jvmTest"

    - stage: test
      name: "Android"
      language: android
      dist: trusty
      android:
        components:
          - build-tools-29.0.2
          - android-29
      script: "./gradlew clean testDebugUnitTest"