install: skip

stages:
  - "Unit test"
  - "Integration test"

jobs:
  include:
    - stage: "Unit test"
      name: "MacOS"
      os: osx
      osx_image: xcode11
      language: java
      script: "./gradlew macosX64Test iosX64Test"

    - stage: "Unit test"
      name: "Linux"
      os: linux
      language: java
      script: "./gradlew clean linuxX64Test"

    - stage: "Unit test"
      name: "JavaScript unit test"
      language: java
      script: "./gradlew clean jsTest jsNodeTest"

    - stage: "Unit test"
      name: "JVM unit tests"
      language: java
      script: "./gradlew clean jvmTest"

    - stage: "Unit test"
      name: "Android"
      language: android
      dist: trusty
      android:
        components:
          - build-tools-29.0.2
          - android-29
      script: "./gradlew clean testDebugUnitTest"

    - stage: "Integration test"
      name: "MacOS"
      os: osx
      osx_image: xcode11
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishMacosX64PublicationToMavenLocal publishIosX64PublicationToMavenLocal publishIosArm64PublicationToMavenLocal mmock-compiler-plugin:publishToMavenLocal mmock-compiler-plugin-native:publishToMavenLocal mmock-gradle-plugin:publishToMavenLocal"
      script:
        - "cd demo-project"
        - "./gradlew clean macosX64Test iosX64Test"

    - stage: "Integration test"
      name: "Linux"
      os: linux
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishLinuxX64PublicationToMavenLocal mmock-compiler-plugin:publishToMavenLocal mmock-compiler-plugin-native:publishToMavenLocal mmock-gradle-plugin:publishToMavenLocal"
      script:
        - "cd demo-project"
        - "./gradlew clean linuxX64Test"

    - stage: "Integration test"
      name: "JavaScript"
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishLinuxX64PublicationToMavenLocal publishJsPublicationToMavenLocal mmock-compiler-plugin:publishToMavenLocal mmock-compiler-plugin-native:publishToMavenLocal mmock-gradle-plugin:publishToMavenLocal"
      script:
        - "cd demo-project"
        - "./gradlew clean jsTest jsNodeTest"

    - stage: "Integration test"
      name: "JVM"
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishLinuxX64PublicationToMavenLocal publishJvmPublicationToMavenLocal mmock-compiler-plugin:publishToMavenLocal mmock-compiler-plugin-native:publishToMavenLocal mmock-gradle-plugin:publishToMavenLocal"
      script:
        - "cd demo-project"
        - "./gradlew clean jvmTest"

    - stage: "Integration test"
      name: "Android"
      language: android
      dist: trusty
      android:
        components:
          - build-tools-29.0.2
          - android-29
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishLinuxX64PublicationToMavenLocal publishAndroidDebugPublicationToMavenLocal publishAndroidReleasePublicationToMavenLocal mmock-compiler-plugin:publishToMavenLocal mmock-compiler-plugin-native:publishToMavenLocal mmock-gradle-plugin:publishToMavenLocal"
      script:
        - "cd demo-project"
        - "./gradlew clean testDebugUnitTest"