install: skip

jobs:
  include:
    - stage: test
      name: "MacOS unit tests"
      os: osx
      osx_image: xcode11
      language: java
      script: "./gradlew macosX64Test iosX64Test"

    - stage: test
      name: "Linux unit test"
      os: linux
      language: java
      script: "./gradlew clean linuxX64Test"

    - stage: test
      name: "JavaScript unit test"
      language: java
      script: "./gradlew clean jsTest jsNodeTest"

    - stage: test
      name: "JVM unit tests"
      language: java
      script: "./gradlew clean jvmTest"

    - stage: test
      name: "Android unit tests"
      language: android
      dist: trusty
      android:
        components:
          - build-tools-29.0.2
          - android-29
      script: "./gradlew clean testDebugUnitTest"

    - stage: test
      name: "MacOS integration tests"
      os: osx
      osx_image: xcode11
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishMacosX64PublicationToMavenLocal publishIosX64PublicationToMavenLocal publishIosArm64PublicationToMavenLocal mmock-compiler-plugin:publishToMavenLocal mmock-compiler-plugin-native:publishToMavenLocal mmock-gradle-plugin:publishToMavenLocal"
      script:
        - "cd demo-project"
        - "./gradlew clean macosX64Test iosX64Test"

    - stage: test
      name: "Linux integration tests"
      os: linux
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishLinuxX64PublicationToMavenLocal mmock-compiler-plugin:publishToMavenLocal mmock-compiler-plugin-native:publishToMavenLocal mmock-gradle-plugin:publishToMavenLocal"
      script:
        - "cd demo-project"
        - "./gradlew clean linuxX64Test"

    - stage: test
      name: "JavaScript integration tests"
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishJsPublicationToMavenLocal mmock-compiler-plugin:publishToMavenLocal mmock-compiler-plugin-native:publishToMavenLocal mmock-gradle-plugin:publishToMavenLocal"
      script:
        - "cd demo-project"
        - "./gradlew clean jsTest jsNodeTest"

    - stage: test
      name: "JVM integration tests"
      language: java
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishJvmPublicationToMavenLocal mmock-compiler-plugin:publishToMavenLocal mmock-compiler-plugin-native:publishToMavenLocal mmock-gradle-plugin:publishToMavenLocal"
      script:
        - "cd demo-project"
        - "./gradlew clean jvmTest"

    - stage: test
      name: "Android integration tests"
      language: android
      dist: trusty
      android:
        components:
          - build-tools-29.0.2
          - android-29
      before_script: "./gradlew -Prelease.version=0.0.0-SNAPSHOT clean publishMetadataPublicationToMavenLocal publishKotlinMultiplatformPublicationToMavenLocal publishAndroidDebugPublicationToMavenLocal publishAndroidReleasePublicationToMavenLocal mmock-compiler-plugin:publishToMavenLocal mmock-compiler-plugin-native:publishToMavenLocal mmock-gradle-plugin:publishToMavenLocal"
      script:
        - "cd demo-project"
        - "./gradlew clean testDebugUnitTest"